# Generated by Django 4.0.2 on 2022-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'table',
                'ordering': ['id'],
            },
        ),
    ]
